### PR TITLE
Getting rid of unused code as per the TODO

### PR DESCRIPTION
**Pull request by mr-vaibh**
Commenting out the unused code part

Not deleting it for future reference.

### CODE REVIEW

**Review by zerolab — CHANGES_REQUESTED** [review]
Hey @mr-vaibh, 

Thank you for this PR. Commenting out the code is not getting rid of it, merely delaying the fact. Can you please fully remove it (and the TODO comment?)

**Comment by mr-vaibh** [comment]
@zerolab Did it! :)

**Review by zerolab — APPROVED** [review]
Excellent!

**Comment by mr-vaibh** [comment]
@cnk please merge this PR

**Comment by mr-vaibh** [comment]
@zerolab

**Comment by zerolab** [comment]
This slipped under the radar. Cheers for the nudge @mr-vaibh and thank you for the contribution!

**Pull request merged**
