### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by khushishikhu**
It creates a confusion for a new contributor, as what is the purpose of making "superuser" and how to move ahead.

Added an essential step to ease new contributor

### CODE REVIEW

**Comment by MugoBrian** [comment]
@khushishikhu , this is great but I think the README.md should be kept as simple as possible and clean, since the [docs](https://docs.wagtail.org/en/stable/) extensively explain the getting started process.

I'd like to suggest including the following instead:
"These superuser credentials are essential for accessing the site as an administrator via the /admin route. "

It's worth noting that contributors setting up their codebase in Gitpod are redirected to a different URL, rather than localhost:8000."

**Comment by MugoBrian** [comment]
@khushishikhu, this is great but I think the README.md should be kept as simple as possible and clean, since the [docs](https://docs.wagtail.org/en/stable/) extensively explain the getting started process.

I'd like to suggest including the following instead:
"These superuser credentials are essential for accessing the site as an administrator via the /admin route. "

It's worth noting that contributors setting up their codebase in Gitpod are redirected to a different URL, rather than localhost:8000."

**Comment by MugoBrian** [comment]
Hello @khushishikhu, this is great work, however I believe the README.md should be kept as simple as possible and clean, since the [docs](https://docs.wagtail.org/en/stable/) extensively explain the getting started process.

I'd like to suggest including the following instead:
"These superuser credentials are essential for accessing the site as an administrator via the /admin route. "

It's worth noting that contributors setting up their codebase in Gitpod are redirected to a different URL, rather than localhost:8000."

**Review by thibaudcolas — APPROVED** [review]
Thanks @khushishikhu! As @MugoBrian it’s crucial for us those instructions are quite succinct – so I kept what you added but moved it to the line we already have about which page to open to view the site (and now the admin).

**Pull request merged**
