### PR TITLE
Adjusted display settings to prevent image overflow in textimage blocks

### PR DESCRIPTION
**Pull request by vossisboss**
Images were overflowing from the textimage blocks and were displaying poorly in mobile. I changed the overflow settings and added some media queries to make these blocks display better. Please let me know if you have any suggested changes.

### CODE REVIEW

**Comment by zerolab** [comment]
@vossisboss could you add a representative link/screenshot?

**Comment by vossisboss** [comment]
@zerolab Yup. These are some images from a draft of a new page I'm building. Here is how the images displayed in the block prior to this adjustment. Note how the image bleeds out into the text.
Screen Shot 2022-07-10 at 3 14 31 PM
And note how the image becomes so very tiny in a mobile-size display:
Screen Shot 2022-07-10 at 3 14 45 PM
Here is how the same content looks after the adjustment on a larger screen:
Screen Shot 2022-07-10 at 3 13 28 PM
And on a mobile screen, the image and the text will stack now:
Screen Shot 2022-07-10 at 3 13 45 PM

The most prominent use of this block in existing pages appears to be in the About page and it appears people corrected for the image bleed by adding additional text to expand the grey background. I would prefer not to add unnecessary text to avoid an image bleed.

**Comment by thibaudcolas** [comment]
@vossisboss is this still relevant with our current launch of the updated site?

**Comment by vossisboss** [comment]
This PR is no longer relevant given the move to the new design. Closing it out.

**Pull request closed without merging**
